x-othentic-cli: &othentic-cli
  env_file:
    - .env
  build:
    context: .
    dockerfile: ./Dockerfile

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    tag: "{{.Name}}"

services:
  aggregator:
    <<: *othentic-cli
    command:
      [
        "node",
        "aggregator",
        "--json-rpc",
        "--l1-chain",
        "${L1:-holesky}",
        "--l2-chain",
        "${L2:-base-sepolia}",
        "--metrics",
        "--internal-tasks",
        "--sync-interval",
        "5400000",
      ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_AGGREGATOR}
    ports:
      - "8545:8545"
      - "9876:9876"
    networks:
      p2p:
        ipv4_address: 10.8.0.69

networks:
  p2p:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
